name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - main
      - develop
      - feature/*
      - hotfix/*
      - bugfix/*
      - release/*
  pull_request:
    branches:
      - main
      - develop
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v1.2.1
        with:
          version: v1.31
          github-token: ${{ github.token }}
          args: ./...
